import React from 'react';
import { useNavigate } from 'react-router-dom';
import { useLocation } from "react-router-dom"

 
import {
    Accordion,
    AccordionItem,
    AccordionButton,
    AccordionPanel,
    AccordionIcon,
    Box
} from '@chakra-ui/react'

import Sidebar from "../../../components/layout/Sidebar.jsx";


import { MinusIcon, AddIcon } from '@chakra-ui/icons'
const GlossaryPage = () => {

    const navigate = useNavigate();
    const location = useLocation();
    const meta = {
        title: `${location.pathname} page Indofood`,
        description: `Page of ${location.pathname} from Indofood`,
        canonical: `https://www.indofoodinternational.com/e-order${location.pathname}`,
        meta: {
          charset: 'utf-8',
          name: {
            keywords: 'react,meta,document,html,tags'
          }
        }
      };
    const data = [
        { judul: "Bulk Order", isi: "Bulk order is a feature you can use when you want to place an order for one or two types of products in a quantity of more than 2 containers.", },
        { judul: "Container Load", isi: "Container load is the quantity of a product that can be loaded into one container.", },
        { judul: "Container Size", isi: "Container Size refers to the size of the container that can be used for shipping products. There are three container sizes available for shipping: 40HC (most commonly used), 40FT, and 20FT.", },
        { judul: "Credit Limit", isi: "Credit limit refers to the maximum amount of credit that a distributor is allowed to extend by purchasing products from Indofood.", },
        { judul: "Draft Order", isi: "Draft order is a list of orders created by the distributor that is not yet ready to be submitted and processed. The order details are still subject to change.", },
        { judul: "Due Day", isi: "Due date is the specific number of days by which a payment must be made for products that have been ordered.", },
        { judul: "ETA", isi: "Estimated Time of Arrival (ETA) is when a ship or vessel is expected to arrive at a specific destination.", },
        { judul: "ETD", isi: "Estimated Time of Departure (ETD) is when a ship or vessel is expected to depart.", },
        { judul: "ETS", isi: "ETS or Estimated Time of Stuffing is the estimated time when the products ordered by the distributor will be loaded at the factory and transported to the port.", },
        { judul: "Flavour I & Flavour II", isi: "Flavour I and Flavour II refer to the product names that can be ordered in a single container. The quantities for Flavour I and II are automatically calculated to meet the full container load quantity.", },
        { judul: "ID", isi: "ID is a unique number generated by e-order as an identity for each distributor's order.", },
        { judul: "MOQ", isi: "MOQ or Minimum Order Quantity is the minimum amount that a distributor must be fulfilled when purchasing products within a one-week shipping time.", },
        { judul: "Notify Email", isi: "The notify email is the email address that will receive notifications about changes in the order status.", },
        { judul: "PO Buyer", isi: "PO Buyer is the distributor's purchase order number that needs to be entered when placing an order in e-order.", },
        { judul: "PO File", isi: "A PO File is a purchase order document created by the distributor. You can attach it when placing an order (not mandatory if you don't have a PO document). The distributor's PO File will help us cross-check with the order you've already submitted in the e-order system.", },
        { judul: "Port", isi: "Port is the destination port where the order will be received by the Distributor according to the agreement specified in the CSI (Customer Shipment Instruction).", },
        { judul: "Product Catalog", isi: "The product catalog displays information about the products available for ordering by the distributor.", },
        { judul: "Remarks", isi: "Remarks are additional notes you can add about the shipment.", },
        { judul: "Ship to Party", isi: "Ship to party is the party that will receive the products ordered by the Distributor. The ship to party can refer to the distributor itself or another party that has a business relationship with the Distributor.", },
        { judul: "Stuffing Week", isi: "Stuffing week is the week when your orders begin to be shipped from Indonesia.", },
        { judul: "Term of Payment", isi: "Term of payment refers to the agreed-upon conditions and timeframe in which a buyer or customer is required to make payment for the goods they have order.", },
        { judul: "Transaction list", isi: "The transaction list shows all the orders submitted by the distributor, including those that have not been processed, are currently being processed, in transit, or already completed.", },


    ];
    const sortedData = data.sort((a, b) => {
        const judulA = a.judul.toLowerCase().trim();
        const judulB = b.judul.toLowerCase().trim();
        if (judulA < judulB) return -1;
        if (judulA > judulB) return 1;
        return 0;
    });

    return (
        <div>
            {/* navbar */}

            <div>
                <div className="py-5 mt-2 stick-left">
                    <div className="row">
                        <div className="col-6 col-sm-12"></div>
                        <div className="col-6 col-sm-12">
                              <Sidebar />
                        </div>
                    </div>
                </div>

                <div className="py-5 w-100">
                    {/* CONTENT BELOW */}

                    <div className=" col-md-11 col-12 mt-3 padding_start_custom ">
                        <div className="pb-5 pt-4 ">
                            <div>
                                <div className="row user-select-none">

                                    <div className="col-12 text-secondary d-flex  pt-1 ps-4 ps-md-0">
                                        <span
                                            onClick={() => navigate("/e-order/dashboard")}
                                            className="pointer grey_text_normal_20px">
                                            e-order /&nbsp;
                                        </span>
                                        <span
                                            onClick={() => navigate("/e-order/help")}
                                            className="pointer grey_text_normal_20px">
                                            Help
                                        </span>
                                        <span className="grey_text_20px">
                                            &nbsp;/ Glossary
                                        </span>
                                    </div>
                                </div>
                                <div className="row pt-4 ps-4">
                                    <div className="col-12 col-md-6">


                                        {sortedData
                                            .filter((_, index) => index % 2 === 0)
                                            .map((data, idx) => (
                                                <>
                                                    <div className="col-12">
                                                        <Accordion key={idx} allowMultiple >
                                                            <AccordionItem className="border shadow shadow-sm py-3 row w-100  help_buttons position-relative mb-4">
                                                                <h2>
                                                                    <AccordionButton>
                                                                        <Box as="span" flex='1' textAlign='left' className="d-flex fw-bold fs-5 justify-content-start text-secondary">
                                                                            {data.judul}
                                                                        </Box>
                                                                        <AccordionIcon />
                                                                    </AccordionButton>
                                                                </h2>
                                                                <AccordionPanel pb={4} textAlign='left'>
                                                                    <div className="px-3 fw-normal fs-5">
                                                                        {data.isi}
                                                                    </div>
                                                                </AccordionPanel>
                                                            </AccordionItem>

                                                        </Accordion>
                                                    </div >
                                                </>
                                            ))}

                                    </div>


                                    <div className="col-12  col-md-6">
                                        {sortedData
                                            .filter((_, index) => index % 2 != 0)
                                            .map((data, idx) => (
                                                <>
                                                    <div className="col-12">
                                                        <Accordion key={idx} allowMultiple >
                                                            <AccordionItem className="border shadow shadow-sm py-3 row w-100  help_buttons position-relative mb-4">
                                                                <h2>
                                                                    <AccordionButton>
                                                                        <Box as="span" flex='1' textAlign='left' className="d-flex fw-bold fs-5 justify-content-start text-secondary">
                                                                            {data.judul}
                                                                        </Box>
                                                                        <AccordionIcon />
                                                                    </AccordionButton>
                                                                </h2>
                                                                <AccordionPanel pb={4} textAlign='left'>
                                                                    <div className="px-3 fw-normal fs-5">
                                                                        {data.isi}
                                                                    </div>
                                                                </AccordionPanel>
                                                            </AccordionItem>

                                                        </Accordion>
                                                    </div >
                                                </>
                                            ))}
                                    </div>





                                </div>
                            </div>


                        </div>



                    </div>
                </div>
            </div>
        </div >
    )
}

export default GlossaryPage;




