import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Switch } from '@/components/ui/switch';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Button } from '@/components/ui/button';
import {
    Accordion,
    AccordionContent,
    AccordionItem,
    AccordionTrigger,
} from '@/components/ui/accordion';
import {
    Settings,
    Bell,
    Lock,
    Palette,
    FileText,
    Code,
    Users,
    Mail,
    Webhook,
    Database,
} from 'lucide-react';

interface ServiceSettingsTabProps {
    serviceId: string;
    settings: ServiceSettings;
    onChange: (settings: ServiceSettings) => void;
}

export interface ServiceSettings {
    // Appearance
    icon?: string;
    color?: string;
    showInCatalog?: boolean;

    // Access Control
    allowedRoles?: string[];
    allowedDepartments?: string[];
    requireApproval?: boolean;

    // Notifications
    emailOnSubmit?: boolean;
    emailOnApprove?: boolean;
    emailOnReject?: boolean;
    emailRecipients?: string;

    // Document Generation
    documentTemplateId?: string;
    autoGenerateDocument?: boolean;

    // Advanced
    apiEndpoint?: string;
    webhookUrl?: string;
    customCss?: string;
    debugMode?: boolean;
}

export const ServiceSettingsTab: React.FC<ServiceSettingsTabProps> = ({
    serviceId,
    settings,
    onChange,
}) => {
    const updateSetting = <K extends keyof ServiceSettings>(key: K, value: ServiceSettings[K]) => {
        onChange({ ...settings, [key]: value });
    };

    return (
        <div className="space-y-6">
            <Accordion type="multiple" defaultValue={['appearance', 'notifications']} className="space-y-4">

                {/* Appearance Settings */}
                <AccordionItem value="appearance" className="border rounded-lg">
                    <AccordionTrigger className="px-4 hover:no-underline">
                        <div className="flex items-center gap-2">
                            <Palette className="w-4 h-4 text-purple-500" />
                            <span className="font-medium">Appearance</span>
                        </div>
                    </AccordionTrigger>
                    <AccordionContent className="px-4 pb-4">
                        <div className="grid grid-cols-2 gap-4">
                            <div className="space-y-2">
                                <Label className="text-xs text-gray-500">Service Icon (Emoji)</Label>
                                <Input
                                    value={settings.icon || '📋'}
                                    onChange={(e) => updateSetting('icon', e.target.value)}
                                    placeholder="📋"
                                    className="w-20 text-center text-2xl"
                                />
                            </div>
                            <div className="space-y-2">
                                <Label className="text-xs text-gray-500">Theme Color</Label>
                                <Input
                                    type="color"
                                    value={settings.color || '#3b82f6'}
                                    onChange={(e) => updateSetting('color', e.target.value)}
                                    className="h-10 w-20"
                                />
                            </div>
                            <div className="col-span-2 flex items-center justify-between py-2">
                                <div>
                                    <Label>Show in Service Catalog</Label>
                                    <p className="text-xs text-gray-500">Make this service visible to users</p>
                                </div>
                                <Switch
                                    checked={settings.showInCatalog !== false}
                                    onCheckedChange={(checked) => updateSetting('showInCatalog', checked)}
                                />
                            </div>
                        </div>
                    </AccordionContent>
                </AccordionItem>

                {/* Access Control */}
                <AccordionItem value="access" className="border rounded-lg">
                    <AccordionTrigger className="px-4 hover:no-underline">
                        <div className="flex items-center gap-2">
                            <Lock className="w-4 h-4 text-orange-500" />
                            <span className="font-medium">Access Control</span>
                        </div>
                    </AccordionTrigger>
                    <AccordionContent className="px-4 pb-4">
                        <div className="space-y-4">
                            <div className="space-y-2">
                                <Label className="text-xs text-gray-500">Allowed Roles (comma-separated)</Label>
                                <Input
                                    value={settings.allowedRoles?.join(', ') || ''}
                                    onChange={(e) => updateSetting('allowedRoles', e.target.value.split(',').map(s => s.trim()).filter(Boolean))}
                                    placeholder="admin, manager, user"
                                />
                            </div>
                            <div className="space-y-2">
                                <Label className="text-xs text-gray-500">Allowed Departments (comma-separated)</Label>
                                <Input
                                    value={settings.allowedDepartments?.join(', ') || ''}
                                    onChange={(e) => updateSetting('allowedDepartments', e.target.value.split(',').map(s => s.trim()).filter(Boolean))}
                                    placeholder="IT, HR, Finance"
                                />
                            </div>
                            <div className="flex items-center justify-between py-2">
                                <div>
                                    <Label>Require Approval</Label>
                                    <p className="text-xs text-gray-500">Submissions require manager approval</p>
                                </div>
                                <Switch
                                    checked={settings.requireApproval !== false}
                                    onCheckedChange={(checked) => updateSetting('requireApproval', checked)}
                                />
                            </div>
                        </div>
                    </AccordionContent>
                </AccordionItem>

                {/* Notifications */}
                <AccordionItem value="notifications" className="border rounded-lg">
                    <AccordionTrigger className="px-4 hover:no-underline">
                        <div className="flex items-center gap-2">
                            <Bell className="w-4 h-4 text-blue-500" />
                            <span className="font-medium">Notifications</span>
                        </div>
                    </AccordionTrigger>
                    <AccordionContent className="px-4 pb-4">
                        <div className="space-y-4">
                            <div className="flex items-center justify-between py-2">
                                <Label>Email on Submit</Label>
                                <Switch
                                    checked={settings.emailOnSubmit || false}
                                    onCheckedChange={(checked) => updateSetting('emailOnSubmit', checked)}
                                />
                            </div>
                            <div className="flex items-center justify-between py-2">
                                <Label>Email on Approve</Label>
                                <Switch
                                    checked={settings.emailOnApprove || false}
                                    onCheckedChange={(checked) => updateSetting('emailOnApprove', checked)}
                                />
                            </div>
                            <div className="flex items-center justify-between py-2">
                                <Label>Email on Reject</Label>
                                <Switch
                                    checked={settings.emailOnReject || false}
                                    onCheckedChange={(checked) => updateSetting('emailOnReject', checked)}
                                />
                            </div>
                            <div className="space-y-2">
                                <Label className="text-xs text-gray-500">Additional Email Recipients</Label>
                                <Input
                                    value={settings.emailRecipients || ''}
                                    onChange={(e) => updateSetting('emailRecipients', e.target.value)}
                                    placeholder="admin@company.com, manager@company.com"
                                />
                            </div>
                        </div>
                    </AccordionContent>
                </AccordionItem>

                {/* Document Generation */}
                <AccordionItem value="documents" className="border rounded-lg">
                    <AccordionTrigger className="px-4 hover:no-underline">
                        <div className="flex items-center gap-2">
                            <FileText className="w-4 h-4 text-green-500" />
                            <span className="font-medium">Document Generation</span>
                        </div>
                    </AccordionTrigger>
                    <AccordionContent className="px-4 pb-4">
                        <div className="space-y-4">
                            <div className="flex items-center justify-between py-2">
                                <div>
                                    <Label>Auto-Generate Document</Label>
                                    <p className="text-xs text-gray-500">Generate PDF on approval</p>
                                </div>
                                <Switch
                                    checked={settings.autoGenerateDocument || false}
                                    onCheckedChange={(checked) => updateSetting('autoGenerateDocument', checked)}
                                />
                            </div>
                            <div className="space-y-2">
                                <Label className="text-xs text-gray-500">Document Template ID</Label>
                                <Input
                                    value={settings.documentTemplateId || ''}
                                    onChange={(e) => updateSetting('documentTemplateId', e.target.value)}
                                    placeholder="e.g., srf_template_1"
                                />
                            </div>
                        </div>
                    </AccordionContent>
                </AccordionItem>

                {/* Advanced Settings */}
                <AccordionItem value="advanced" className="border rounded-lg">
                    <AccordionTrigger className="px-4 hover:no-underline">
                        <div className="flex items-center gap-2">
                            <Code className="w-4 h-4 text-gray-500" />
                            <span className="font-medium">Advanced</span>
                        </div>
                    </AccordionTrigger>
                    <AccordionContent className="px-4 pb-4">
                        <div className="space-y-4">
                            <div className="space-y-2">
                                <Label className="text-xs text-gray-500">API Endpoint Override</Label>
                                <Input
                                    value={settings.apiEndpoint || ''}
                                    onChange={(e) => updateSetting('apiEndpoint', e.target.value)}
                                    placeholder="/api/custom-endpoint"
                                    className="font-mono text-xs"
                                />
                            </div>
                            <div className="space-y-2">
                                <Label className="text-xs text-gray-500">Webhook URL</Label>
                                <Input
                                    value={settings.webhookUrl || ''}
                                    onChange={(e) => updateSetting('webhookUrl', e.target.value)}
                                    placeholder="https://..."
                                    className="font-mono text-xs"
                                />
                            </div>
                            <div className="space-y-2">
                                <Label className="text-xs text-gray-500">Custom CSS</Label>
                                <Textarea
                                    value={settings.customCss || ''}
                                    onChange={(e) => updateSetting('customCss', e.target.value)}
                                    placeholder=".form-container { ... }"
                                    className="font-mono text-xs h-24"
                                />
                            </div>
                            <div className="flex items-center justify-between py-2">
                                <div>
                                    <Label>Debug Mode</Label>
                                    <p className="text-xs text-gray-500">Show debug info in console</p>
                                </div>
                                <Switch
                                    checked={settings.debugMode || false}
                                    onCheckedChange={(checked) => updateSetting('debugMode', checked)}
                                />
                            </div>
                        </div>
                    </AccordionContent>
                </AccordionItem>

            </Accordion>
        </div>
    );
};

export default ServiceSettingsTab;
