-- =============================================================
-- DATABASE INDEX OPTIMIZATION SCRIPT
-- Generated by: AntiGravity AI
-- Purpose: Speed up HOTS Dashboard Latency
-- =============================================================

-- 1. Optimizing "My Pending Approvals" Query
-- Query: WHERE approver_id = ? AND approval_status = 0
CREATE INDEX idx_ticket_event_approver_status 
ON t_ticket_event (approver_id, approval_status);

-- 2. Optimizing "My Open Tickets" Query
-- Query: WHERE created_by = ? AND status_id ...
CREATE INDEX idx_ticket_creator_status 
ON t_ticket (created_by, status_id);

-- 3. Optimizing "Assignments" Query
-- Query: WHERE assignment_status = 'active' AND assigned_type = ...
CREATE INDEX idx_assignment_lookup 
ON t_ticket_assignment (assignment_status, assigned_type, assigned_id);

-- 4. Optimizing "Service Reports" & "Date Ranges"
-- This is CRITICAL for all the "This Week", "This Month", and "Sparkline" queries
-- Query: WHERE service_id = ? AND creation_date >= ?
CREATE INDEX idx_ticket_service_date 
ON t_ticket (service_id, creation_date);

-- 5. Fallback for date-only queries (e.g. "Tickets This Week" - global)
CREATE INDEX idx_ticket_creation_date 
ON t_ticket (creation_date);

-- =============================================================
-- HOW TO CHECK IF IT WORKS:
-- Run "EXPLAIN" before and after adding these indexes on your heavy queries.
-- You should see "key" column changing from NULL to these index names.
-- =============================================================
